openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  /:
    get:
      summary: Read Index
      operationId: read_index__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /paraphrase/:
    post:
      summary: Main
      operationId: main_paraphrase__post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
